name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:

  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: 'Terraform Setup'
        run: |
          wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
          unzip terraform_0.12.24_linux_amd64.zip
          sudo mv terraform /usr/local/bin
          rm terraform_0.12.24_linux_amd64.zip
      - name: 'Terraform Init'
        run: |
          cd infra/
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Build lambda packages'
        run: |
          mkdir -p src/packages
          pip install --system -r src/poe_ladder_exporter/requirements.txt --target src/packages
          cd src/packages && zip -r9 ../poe_ladder_exporter-${GITHUB_SHA}.zip .
          cd ../ && zip -ur poe_ladder_exporter-${GITHUB_SHA}.zip poe_ladder_exporter
          rm -rf packages
          cd ../ && mkdir -p src/packages
          pip install --system -r src/poe_character_exporter/requirements.txt --target src/packages
          cd src/packages && zip -r9 ../poe_character_exporter-${GITHUB_SHA}.zip .
          cd ../ && zip -ur poe_character_exporter-${GITHUB_SHA}.zip poe_character_exporter
          rm -rf packages
      - name: 'Terraform plan'
        run: |
          cd infra/
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_commit_sha: ${{ github.sha }}
      - name: 'Terraform Apply'
        run: |
          cd infra/
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_commit_sha: ${{ github.sha }}

